Fix msgTypes + Add sort_by/sort_order args to MessageFilter/PostFilter
aleph-im/aleph-sdk-python pull request #104
Opened 2024-02-19 04:03 UTC by philogicae

# Found issues:
- Missing sort_by/sort_order filters: [issue 95 on SDK](https://github.com/aleph-im/aleph-sdk-python/issues/95)
- message_types passed as arg to MessageFilter breaks if nb elements > 1

# Proposed solution:
- Modified MessageFilter/PostFilter + Added SortBy/SortOrder enums
- Fix typo on msgType -> msgTypes

2024-02-19 09:25 UTC, MHHukiewitz submitted a review, later dismissed
.Thank you for the contribution! Also, good finds on msgTypes and enum_as_str :+1:

2024-02-19 11:19 UTC, philogicae commented
Fixed the isort test failing

2024-02-19 17:05 UTC, MHHukiewitz requested changes

2024-02-19 17:05 UTC, MHHukiewitz commented on src/aleph/sdk/utils.py
>          raise TypeError(f"Unsupported enum type: {type(obj)}")
As it stands, just returning an empty string seems risky to me. Please revert the change, if accomodating for the Optional[str] in the return type is too much effort to be worth it.

2024-02-20 11:25 UTC, philogicae commented on src/aleph/sdk/utils.py
>          raise TypeError(f"Unsupported enum type: {type(obj)}")
You are right, I reverted the change. Makes more sense to keep the Optional returned value. But I had to modify chains/common, the tests require null safety.

2024-02-20 14:34 UTC, MHHukiewitz approved these changes

2024-02-20 14:35 UTC, merged