Feature: Allow User to control there VM
aleph-im/aleph-sdk-python pull request #124
Opened 2024-06-12 12:21 UTC by 1yam

Summary
This feature introduces new capabilities for users to manage their virtual machines (VMs) directly. The following functionalities are included:

- Notify instances
- Stop VMs
- Reboot VMs
- Erase VMs
- Expire VMs
- Get Logs (authentication still remaining)

2024-06-12 14:15 UTC, hoh reviewed
Left a few comments.

My main remarks are on changing the pattern from callbacks to async generator, and to add typing annotation.

2024-06-12 14:15 UTC, hoh commented on src/aleph/sdk/client/vmclient.py
> +        self.expected_domain = domain
Why `expected_domain` and not just `domain` ?

2024-06-19 13:16 UTC, hoh commented
Can you add tests on the new code ?

2024-06-25 13:58 UTC, Psycojoker commented
Isn't this whole PR missing any form of documentation '-'?

2024-06-25 16:59 UTC, Psycojoker reviewed
In addition for the review I've added quite some small fixes in this PR to speed up things a bit https://github.com/aleph-im/aleph-sdk-python/pull/135

2024-06-25 16:59 UTC, Psycojoker commented on src/aleph/sdk/client/vmclient.py
> +    def create_payload(self, vm_id: str, operation: str) -> Dict[str, str]:
Does this function make sens as a public function?

2024-06-25 16:59 UTC, Psycojoker commented on src/aleph/sdk/client/vmclient.py
> +    def sign_payload(self, payload: Dict[str, str], ephemeral_key) -> str:
Does this function make sens as a public function?

2024-06-28 13:37 UTC, 1yam commented on tests/unit/aleph_vm_authentication.py
> +def require_jwk_authentication(
Hugo wanted to add authentication checks to the unit tests with this code (parts of aleph-vm repo), but i'm not sure how to manage it with mocking. It could be interesting to do pair programming to check that.

2024-06-28 13:37 UTC, 1yam commented on src/aleph/sdk/client/vmclient.py
> +    async def __aenter__(self):
Other classes of the SDK use it, so I wanted to allow developers to use it as a context manager.

2024-07-03 14:40 UTC, Psycojoker commented on tests/unit/aleph_vm_authentication.py
> +async def authenticate_websocket_message(message) -> str:
It's for test, we use it now

2024-07-04 07:03 UTC, olethanh requested changes

2024-07-04 07:03 UTC, olethanh commented on src/aleph/sdk/client/vmclient.py
> +        payload = create_vm_control_payload(vm_id, "logs")
I have renamed the endpoint in the PR here https://github.com/aleph-im/aleph-vm/pull/645 that just go merged 

```suggestion
        payload = create_vm_control_payload(vm_id, "stream_logs")
```

2024-07-04 09:55 UTC, olethanh requested changes
Please wait before merging. I have encountered a few bug while testing them again the CRN.
I will provide fix for them

2024-07-04 13:04 UTC, olethanh commented on src/aleph/sdk/client/vmclient.py
> +                "content": {"domain": urlparse(self.node_url).netloc},
Not sure what the `sender` and `content` thing are for, they aren't needed by the server

2024-07-04 15:35 UTC, nesitor requested changes

2024-07-04 15:35 UTC, nesitor commented on tests/unit/test_vmclient.py
> +        await vm_client.session.close()
All these tests aren't so useful, just to test that a http call is done, but doesn't check either the arguments and the number of calls neither.

2024-07-04 15:35 UTC, nesitor commented on src/aleph/sdk/client/vmclient.py
> +                "content": {"domain": urlparse(self.node_url).netloc},
I agree, the `sender` should be the same than `pubkey` key on the payload, and the same for the `domain` key on the content field.

2024-07-04 20:35 UTC, olethanh approved these changes
I have done the modification in the `andres-feature-implement_confidential_vm_initialization` branch and merge dinto this one.

For me we can merge this PR. there are still some possible amelioration on the test and doc but these can be done in a sparate PR

2024-07-04 20:39 UTC, nesitor approved these changes

2024-07-04 20:55 UTC, Psycojoker commented
> there are still some possible amelioration on the test and doc but these can be done in a separate PR

Have you open a clickup ticket for that?

2024-07-05 09:56 UTC, merged

2024-07-05 10:07 UTC, olethanh commented
@Psycojoker https://app.clickup.com/24395970/v/l/6-901502681758-1