Feature: Uses could not use custom timeout
aleph-im/aleph-sdk-python pull request #18
Opened 2023-03-10 12:25 UTC by hoh

2023-03-31 15:13 UTC, odesenfans requested changes

2023-03-31 15:13 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        self.http_session = aiohttp.ClientSession(base_url=api_server, timeout=timeout)
You can't pass `None` as a default, there's a sentinel object in the code of aiohttp. It's gonna have to be something like this:

```suggestion
        params = {"base_url": api_server}
        if timeout:
            params["timeout"] = timeout
        self.http_server = aiohttp.ClientSession(**params)
```

2023-05-10 10:05 UTC, hoh commented on src/aleph/sdk/client.py
> +        self.http_session = aiohttp.ClientSession(base_url=api_server, timeout=timeout)
What about `timeout = timeout or aiohttp.client.sentinel` ?

2023-05-15 22:08 UTC, closed without merging

2023-05-15 22:09 UTC, hoh commented
Replaced in  #24