Fix: SDK error when retrieving fallback private key, but the symlink was dead.
aleph-im/aleph-sdk-python pull request #33
Opened 2023-07-05 10:34 UTC by 1yam

Problem: The symlink can exist, but it can be dead. For example, unit tests may remove the file but not the symlink.

Solution: We add a check to determine if it is a symlink and if it is dead. In this case, we unlink it.

2023-07-05 10:52 UTC, odesenfans requested changes
Hablo ingles?

2023-07-05 10:52 UTC, odesenfans commented on src/aleph/sdk/chains/common.py
> +        # We check if the symlink exist but dead to remove it
```suggestion
        # If the symlink exists but does not point to a file, delete it.
```

2023-07-05 10:52 UTC, odesenfans commented on src/aleph/sdk/chains/common.py
> +        # We create the symlink if symlink not exist
Keep the old comment?
```suggestion
        # Create a symlink to use this key by default
```

2023-07-05 21:52 UTC, hoh commented on src/aleph/sdk/chains/common.py
> +            default_key_path.unlink()
Can you log a warning in this case ? See the use of `logging` in other files.

2023-07-06 09:12 UTC, 1yam commented on src/aleph/sdk/chains/common.py
> +            default_key_path.unlink()
Fix in a418aafd1ce416199721d3d5e43627b9fe62414b

2023-07-06 14:30 UTC, odesenfans approved these changes

2023-07-07 08:18 UTC, merged