Feature: download on ipfs client
aleph-im/aleph-sdk-python pull request #36
Opened 2023-07-10 15:13 UTC by 1yam

Solutions:
   - Add a function called download_file_ipfs that downloads from ipfs.io/ipfs/.
   - Refactor the current download process to include:
      - Chunk size and storage into a buffer (BytesIO). (memory friendly)
   - Add a test for the download functionality.

2023-07-10 15:29 UTC, hoh commented on src/aleph/sdk/client.py
> +            async with session.get(f"https://ipfs.io/ipfs/{file_hash}") as response:
Can you use the IPFS server from aleph.im instead ?

2023-07-10 15:29 UTC, hoh commented on src/aleph/sdk/client.py
> +            async with session.get(f"https://api1.aleph.im/api/v0/storage/raw/{file_hash}") as response:
Using our load balancer would help keeping this work when server api1 is under maintenance.
```suggestion
            async with session.get(f"https://official.aleph.im/api/v0/storage/raw/{file_hash}") as response:
```

There is already a setting in the SDK that points to the API server, `settings.API_HOST`.

2023-07-10 15:29 UTC, hoh commented on src/aleph/sdk/client.py
> +            async with session.get(f"https://ipfs.io/ipfs/{file_hash}") as response:
Can you use the IPFS server from aleph.im instead ?
```suggestion
            async with session.get(f"https://ipfs.aleph.im/ipfs/{file_hash}") as response:
```

2023-07-10 15:29 UTC, hoh commented on src/aleph/sdk/client.py
> +        buffer = BytesIO()
Does this mean that everything is copied in memory ? What if the user downloads a 20 GB file ?

2023-07-10 15:55 UTC, odesenfans requested changes

2023-07-10 15:55 UTC, odesenfans commented on src/aleph/sdk/client.py
> +    def download_file(self, file_hash: str, chunk_size :int = 16 * 1024) -> bytes:
I see some formatting issues, apply black to your branch.

2023-07-10 15:55 UTC, odesenfans commented on src/aleph/sdk/client.py
> +    def download_file(self, file_hash: str, chunk_size :int = 16 * 1024) -> bytes:
I don't think the chunk size needs to be part of the public API, it's an implementation detail. Implement it as a configuration variable or even as a constant in the code.

2023-07-10 15:55 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        :param self: The current instance of the class.
You can omit documentation for `self`.

2023-07-10 15:55 UTC, odesenfans commented on src/aleph/sdk/client.py
> +            async with session.get(f"https://api1.aleph.im/api/v0/storage/raw/{file_hash}") as response:
Use `self.http_session`, we initialize one session when creating the `AlephClient` object.

2023-07-10 15:55 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        buffer = BytesIO()
This function returns the file as bytes, so there's little to be done about this issue. @1yam just preserved the public API, but I think we need to change the signature of this function to return `None` and just write to the file system. Same for `download_file_ipfs` below.

2023-07-10 15:55 UTC, odesenfans commented on tests/unit/test_download.py
> +            file_content = client.download_file("QmeomffUNfmQy76CQGy9NdmqEnnHU9soCexBnGU3ezPHVH")  # File is 5B
Use the async version in your tests.

2023-07-10 15:55 UTC, odesenfans commented on tests/unit/test_download.py
> +    with AlephClient(
`async with`

2023-07-10 15:55 UTC, odesenfans commented on tests/unit/test_download.py
> +        except Exception as e:
No need to catch the exception here, you can let `pytest` catch the exception and log it.

2023-07-10 15:55 UTC, odesenfans commented on tests/unit/test_download.py
> +        assert file_size == 5
Just compare to the expected content of the file, if it's 5 bytes you can just hardcode it.

2023-07-10 15:57 UTC, hoh commented on src/aleph/sdk/client.py
> +        buffer = BytesIO()
Returning a [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) would make more sense than returning `None`

2023-07-10 16:03 UTC, hoh commented on src/aleph/sdk/client.py
> +        buffer = BytesIO()
https://github.com/aleph-im/aleph-sdk-python/issues/37

2023-07-10 16:32 UTC, 1yam commented on src/aleph/sdk/client.py
> +            async with session.get(f"https://ipfs.io/ipfs/{file_hash}") as response:
https://github.com/1yam/aleph-sdk-python/blob/cea3efb270ff6a5161a3a9f788e59e47ae9c1050/src/aleph/sdk/client.py#L661

2023-07-10 16:32 UTC, 1yam commented on src/aleph/sdk/client.py
> +    def download_file(self, file_hash: str, chunk_size :int = 16 * 1024) -> bytes:
fixed

2023-07-10 16:32 UTC, 1yam commented on src/aleph/sdk/client.py
> +        :param self: The current instance of the class.
fix

2023-07-11 13:52 UTC, odesenfans requested changes

2023-07-11 13:52 UTC, odesenfans commented on src/aleph/sdk/client.py
> +    def download_file(self, file_hash: str, chunk_size: int = 16 * 1024) -> bytes:
I still don't think the chunk size should appear in public functions.

2023-07-11 13:52 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        IPFS_HASH = ItemHash(file_hash)
Why upper case? Also you don't need this variable if the file is downloaded through the API. Move it in the if 413 condition..

2023-07-11 13:52 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                        raise Exception("Unsupported file hash")
Raising `Exception` is too broad because it makes it hard for users to determine the nature of the problem. Here the problem is not that we do not support other hash types, it's just that the file is too big to be downloaded through the API. What you should do is create a `FileTooLarge` exception in the `exceptions.py` module and raise it here.

2023-07-11 13:52 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                    response.raise_for_status()
This is useless, no need to `raise_for_status()` if you know that the HTTP code is 200. `raise_for_status()` only raises an exception for 4xx/5xx HTTP codes.

2023-07-11 13:52 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                        output_buffer.write(chunk)
This code is duplicated when reading from IPFS as well. Could you encapsulate it in a function?

Ex:

```
from typing import Protocol, TypeVar

T = TypeVar("T", bytes, str)


class AsyncReadable(Protocol[T]):
  async def read(n: int = -1) -> T:
    ...

class Writable(Protocol[T]):
  def write(buffer: T) -> int:
    ...

async def copy_async_readable_to_buffer(readable: AsyncReadable[T], buffer: Writable[T], chunk_size: int):
  ...
```

2023-07-12 08:47 UTC, odesenfans requested changes

2023-07-12 08:47 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                raise FileTooLarge(f"The file from {file_hash} is too large")
The logic is still not what's needed. Here you replace the URL directly to go to the IPFS service, which is not what we want. I want to go by default to the aleph.im network and then fall back to the IPFS service if we encounter a 413. I don't want to overload the IPFS service for small files.

2023-07-12 08:47 UTC, odesenfans commented on src/aleph/sdk/client.py
> +async def download_file_to_buffer(
Why did you make it a function instead of a method? I think this function is quite convenient to keep inside of `AlephClient`.

2023-07-12 08:47 UTC, odesenfans commented on src/aleph/sdk/exceptions.py
> +    A file is too large
Fair enough.

2023-07-12 11:48 UTC, odesenfans requested changes

2023-07-12 11:48 UTC, odesenfans commented on src/aleph/sdk/client.py
> +C = TypeVar("C", str, bytes, covariant=True)
You can simply use `T = TypeVar("T", str, bytes, covariant=True)`, it's supposed to work.

2023-07-12 11:48 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        buffer.write(chunk)
Also, maybe move the implementation of this function in a new module, like `aleph.sdk.toolkit.io`.

2023-07-12 11:48 UTC, odesenfans commented on src/aleph/sdk/client.py
> +        async with aiohttp.ClientSession() as session:
This session is not used.

2023-07-12 11:48 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                    if ItemType.from_hash(ipfs_hash) == ItemType.ipfs:
You can directly use `ipfs_hash.item_type`.

2023-07-12 11:48 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                elif response.status == 413:
This call will not return a 413, remove this branch.

2023-07-12 13:10 UTC, odesenfans submitted a review, later dismissed

2023-07-12 14:16 UTC, odesenfans approved these changes

2023-07-12 14:18 UTC, merged