AlephClientBase and AuthenticatedAlephClientBase
aleph-im/aleph-sdk-python pull request #54
Opened 2023-08-28 13:20 UTC by MHHukiewitz

Adding abstract base classes for the client classes and add several improvements:
- Many pages of messages can now be iterated over with `get_messages_iterator` or `get_posts_iterator`.
- `get_posts` now returns a `PostsResponse` type instead of untyped dictionary
- Harmonize `get_messages` and `watch_messages` as both should have the same query parameters
- Moved all docstrings from the client classes to their ABCs

2023-08-28 15:17 UTC, hoh commented
Thanks for this proposal for improving the SDK.

The capability of using generators such as your suggestion for `get_messages_iterator` seems very relevant.

I believe that there is a better way of doing this than adding such method, and I experimented a bit with a new Pull Request here: https://github.com/aleph-im/aleph-sdk-python/pull/58

2023-09-05 15:35 UTC, odesenfans requested changes

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/base.py
> +class AlephClientBase(ABC):
Nitpick: style-wise, I'd use `BaseAlephClient` for consistency with the rest of the code base.

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/client.py
> +            True if ignore_invalid_messages is None else ignore_invalid_messages
It's weird to check for `None` if the typing is explicitly stating that the value cannot be `None`. Either keep `Optional` in the signature or assume the breaking change (either raise an exception or emit a warning).

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/client.py
> +            # aleph-message. This allows the user to specify how errors should be handled.
Really?

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                    message = parse_message(post_raw)
A post is not a message so calling `parse_message` looks like a bug.

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/client.py
> +                except KeyError as e:
I don't understand how you'd get a `KeyError`?

2023-09-05 15:35 UTC, odesenfans commented on src/aleph/sdk/client.py
> +    ) -> PostsResponse:
This method should be tested.

2023-09-06 10:18 UTC, MHHukiewitz commented
> Thanks for this proposal for improving the SDK.
> 
> The capability of using generators such as your suggestion for `get_messages_iterator` seems very relevant.
> 
> I believe that there is a better way of doing this than adding such method, and I experimented a bit with a new Pull Request here: #58

Merging the PRs that are lined up would conflict with the proposed changes in #58. I would offer to take these suggested changes and make another PR that integrates better with the new ABCs and MessageCache/DomainNode classes.

2023-09-21 07:38 UTC, MHHukiewitz commented on .coveragerc
> +    pass
![Screenshot from 2023-09-21 09-36-36](https://github.com/aleph-im/aleph-sdk-python/assets/70762838/2c5930ad-ec8b-4f0e-8a50-3a4d39c7c833)

2023-09-21 07:40 UTC, MHHukiewitz commented on src/aleph/sdk/base.py
> +        but will always return all messages.
Then it will return some messages as duplicates, as we do not have cursors. But it will always iterate through all messages

2023-09-21 07:40 UTC, MHHukiewitz commented on cache/files/QmAndSoOn
> +HELLO
Already removed, a test artifact

2023-09-21 08:28 UTC, MHHukiewitz commented on src/aleph/sdk/base.py
> +    async def get_messages_iterator(
We need to pass parameters, which with __aiter__ alone is not possible. Using the structure from `MessageResponse` in #58 we could realize this on the returned object like
```py
messages = client.get_messages(...)
async for message in messages:
    # do something
```
I'd like to expand on this idea when fully implementing this Response Object pattern, as outlined here: https://github.com/aleph-im/aleph-sdk-python/pull/58#discussion_r1330253053

2023-09-27 13:15 UTC, MHHukiewitz commented on src/aleph/sdk/client.py
> +            True if ignore_invalid_messages is None else ignore_invalid_messages
The same was already being done on `get_messages()`, so I just went with the convention.

2023-09-27 13:19 UTC, MHHukiewitz commented on src/aleph/sdk/client.py
> +    ) -> PostsResponse:
It is being done here: https://github.com/aleph-im/aleph-sdk-python/pull/54/files#diff-2639bf9b7e8b37d16d2b7bc98a2e85e7b51600f8329276805b962b194e117f6bR68

2023-09-27 13:22 UTC, MHHukiewitz commented
@hoh and me agreed to continue with merging the branch after another review. I will take care of implementing certain features of #58 in future PRs on the basis of this PR and #59, but will now prioritize UX, especially around deployment and managing of VMs, as new features will hit https://github.com/aleph-im/aleph-vm soon.

@odesenfans please review the requested changes and approve, if no further required.

2023-09-27 13:39 UTC, odesenfans approved these changes

2023-09-27 16:37 UTC, merged